package com.caimao.gjs.api.base.framework;

import java.util.List;
import java.util.Map;

public interface BaseMapper<T,PK> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Sun Aug 11 16:48:40 CST 2013
     */
    int deleteByPrimaryKey(PK id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Sun Aug 11 16:48:40 CST 2013
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Sun Aug 11 16:48:40 CST 2013
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Sun Aug 11 16:48:40 CST 2013
     */
    T selectByPrimaryKey(PK id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Sun Aug 11 16:48:40 CST 2013
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Sun Aug 11 16:48:40 CST 2013
     */
    int updateByPrimaryKey(T record);

    List<T> selectPageList(Map map);

    List<T> selectList(Map map);
    
    int selectCount(Map map);
}